#!/bin/bash
rm -rf /usr/share/lilac/Packages/BioArchLinux/*/src
python /usr/share/lilac/Tools/cleaner/lilac-cleaner -f
python /usr/share/lilac/Tools/cleaner/repocleaner
chown -R bio:pkg /usr/share/lilac/Packages/BioArchLinux/*
